import os

# FLASK
DEBUG = True
SERVER_NAME = ""
SESSION_COOKIE_DOMAIN = ""
MAX_CONTENT_LENGTH = 16 * 1024 * 1024
UPLOAD_FOLDER = "/uploads/"
SECRET_KEY = b""
SENTRY_DSN = ""

# FLASK WTF
WTF_CSRF_SECRET_KEY = os.urandom(32)

# FLASK MAIL
MAIL_DEBUG = True
MAIL_SERVER = "smtp.gmail.com"
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_USERNAME = "@gmail.com"
MAIL_PASSWORD = ""
MAIL_DM = ""
DEFAULT_MAIL_SENDER = ""

# FLASK ADMIN
FLASK_ADMIN_SWATCH = "darkly"

# SQLALCHEMY
SQLALCHEMY_DATABASE_URI = "mysql+pymysql://root:@localhost/secomp"
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_ECHO = False

# SECOMP API
KEY_API_PRESENCA = ""

# PAYPAL SDK
PAYPAL_CLIENT_ID = ""
PAYPAL_CLIENT_SECRET = ""

# GOOGLE RECAPTCHA API
RECAPTCHA_PUBLIC_KEY = ""
RECAPTCHA_PRIVATE_KEY = ""
RECAPTCHA_PARAMETERS = {"hl": "pt-BR"}

# SAGUI API
SAGUI_USER = ""
SAGUI_PASS = ""
