import os

# FLASK
DEBUG = True
MAX_CONTENT_LENGTH = 16*1024*1024
UPLOAD_FOLDER = ''

# FLASK WTF
SECRET_KEY = os.urandom(32)

# FLASK MAIL
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_USERNAME = '@gmail.com'
MAIL_PASSWORD = ''

# FLASK ADMIN
FLASK_ADMIN_SWATCH = 'darkly'

# SQL ALCHEMY
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:12345678@localhost/secomp'
SQLALCHEMY_TRACK_MODIFICATIONS = True

#GOOGLE RECAPTCHA
RECAPTCHA_PUBLIC_KEY = '6LdkbpQUAAAAAGdrsCcAnaNk-IgrNFamcUgDPtrV'
RECAPTCHA_PRIVATE_KEY = '6LdkbpQUAAAAAF30hG53Xwe_vRcak5RDFE_62T0T'