import os

# FLASK
DEBUG = True
MAX_CONTENT_LENGTH = 16*1024*1024
UPLOAD_FOLDER = ''

# FLASK WTF
SECRET_KEY = os.urandom(32)

# FLASK MAIL
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_USERNAME = '@gmail.com'
MAIL_PASSWORD = ''

# FLASK ADMIN
FLASK_ADMIN_SWATCH = 'darkly'

# SQL ALCHEMY
SQLALCHEMY_DATABASE_URI = 'mysql://root:@localhost/db'
SQLALCHEMY_TRACK_MODIFICATIONS = True

#GOOGLE RECAPTCHA
RECAPTCHA_PUBLIC_KEY = ""
RECAPTCHA_PRIVATE_KEY = ""
