import os

# FLASK
DEBUG = True

# FLASK WTF
SECRET_KEY = os.urandom(32)

# FLASK MAIL
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_USERNAME = '@gmail.com'
MAIL_PASSWORD = ''

# FLASK ADMIN
FLASK_ADMIN_SWATCH = 'darkly'

# SQL ALCHEMY
SQLALCHEMY_DATABASE_URI = 'mysql://root:@localhost/db'
SQLALCHEMY_TRACK_MODIFICATIONS = True
